---
- name: install libglib2.0-bin
  become: yes
  apt:
    name: libglib2.0-bin
    state: present
  when: "ansible_pkg_mgr == 'apt'"

- name: configure proxy
  become: yes
  template:
    src: proxy.gschema.override.j2
    dest: "{{ gnome_proxy_glib_schemas_directory }}/{{ gnome_proxy_overide_filename }}"
    owner: root
    group: root
    mode: 'u=rw,go=r'
  notify:
    - comple glib schemas
